### ISSUE TITLE
ACCESS_PASSWORD 环境变量设置的密码无效。

### ISSUE THREAD

**Issue by simonkuang** [qiayue/GitBase#1]
![image](https://github.com/user-attachments/assets/5407a98d-a187-4322-b3ae-a1e2942047e9)

管理后台，`/login`，输入 `ACCESS_PASSWORD` 设置的密码登录，总是报上面的错。

- 尝试过 12 位以上大小写、数字、特殊字符 @ 混合的形式。不行。
- 尝试过 12 位以上大小写、数字混合的形式。不行。
- 尝试过 12 位只有大小写字母的形式。不行。

**Comment by simonkuang** [comment]
补充。

vercel 的 logs 信息如下：
![image](https://github.com/user-attachments/assets/bc734cfb-b389-49fe-bfd5-a237c34b5ade)

其中最关键的 Error 信息如下：
```
⨯ Error: secretOrPrivateKey must have a value
    at e.exports [as sign] (/var/task/.next/server/chunks/482.js:1:7412)
    at s (/var/task/.next/server/app/api/check-auth/route.js:1:1514)
    at p (/var/task/.next/server/app/api/login/route.js:1:873)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /var/task/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36258
    at async eR.execute (/var/task/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:26874)
    at async eR.handle (/var/task/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:37512)
    at async es (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:16:25465)
    at async en.responseCache.get.routeKind (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:1026)
    at async r6.renderToResponseWithComponentsImpl (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:508)
```

**Comment by qiayue** [comment]
原因是登录必须要求所有环境变量都设置正确才行，请先确保在 Vercel 配置了全部环境变量，之后再重新部署一次，等待生效。
<img width="686" alt="image" src="https://github.com/user-attachments/assets/f51f7731-6952-4234-83ab-7f5f89a5d615">

**Comment by simonkuang** [comment]
了解了。我是设置的 vercel env。

能不能同时适配 vercel env，不然的话只能在 github 的 fork sync 和 vercel 的自动部署之间二选一。

- github fork sync。fork 出来的 repo 和 upstream 完全一致，不能 push .env.local 文件。可以手动在 vercel 的 env 里面设置环境变量。
- vercel 自动部署。得自己 push 一个带明文 github token 的 .env.local 文件，但是以后只能手动 sync repo。

**Comment by LiweiDong** [comment]
同样问题， fork的public项目。 不能把.env.local 明文传上去吧。。。 vercel里环境变量已经设置了

**Comment by qiayue** [comment]
Vercel 配置环境变量后，需要重新部署才会生效。另外每一个环境变量都需要设置，尤其是域名不能搞错了，你用哪个域名访问，就要设置哪个。

Liwei Dong ***@***.***> 于2024年8月22日周四 17:24写道：
